# Generated by Django 3.0.6 on 2020-06-15 17:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_dob', models.DateField()),
                ('has_covid', models.BooleanField(default=False)),
                ('patient_lat', models.DecimalField(decimal_places=16, max_digits=22)),
                ('patient_long', models.DecimalField(decimal_places=16, max_digits=22)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('contact_no', models.IntegerField()),
                ('hospital_lat', models.DecimalField(decimal_places=16, max_digits=22)),
                ('hospital_long', models.DecimalField(decimal_places=16, max_digits=22)),
                ('total_beds', models.IntegerField(default=0)),
                ('empty_beds', models.IntegerField(default=0)),
                ('empty_covid_beds', models.IntegerField(default=0)),
                ('testing_kits', models.IntegerField(default=0)),
                ('accepting_patients', models.BooleanField(default=False)),
                ('accepting_covid_patients', models.BooleanField(default=False)),
                ('covid_exclusive', models.BooleanField(default=False)),
                ('government_hospital', models.BooleanField(default=False)),
                ('ambulance_facility', models.BooleanField(default=False)),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
                ('patients_guided_here', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitalapp.Patient')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
