# Generated by Django 3.0.6 on 2020-06-18 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0002_auto_20200617_1655'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hospital',
            old_name='available_ventilators',
            new_name='empty_ventilators',
        ),
        migrations.RenameField(
            model_name='hospital',
            old_name='hospital_lat',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='hospital',
            old_name='hospital_long',
            new_name='longitude',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='patient_lat',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='patient_long',
            new_name='longitude',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='accepting_patients',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='contact_no',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='name',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='testing_kits',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='total_beds',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='patient_dob',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='user',
        ),
        migrations.AddField(
            model_name='hospital',
            name='covid_patients',
            field=models.IntegerField(default=0),
        ),
    ]
