# Generated by Django 3.0.6 on 2020-06-18 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0003_auto_20200618_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='last_updated',
            field=models.TimeField(auto_now=True),
        ),
    ]
