# Generated by Django 3.0.6 on 2020-06-20 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0004_auto_20200618_1500'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Patient',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='user',
        ),
        migrations.AddField(
            model_name='hospital',
            name='email',
            field=models.EmailField(default='example@mail.com', max_length=100),
        ),
        migrations.AddField(
            model_name='hospital',
            name='hospital_name',
            field=models.CharField(default='No Name Provided', max_length=100),
        ),
    ]
