# Generated by Django 3.0.6 on 2020-06-20 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0006_auto_20200620_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='email',
            field=models.EmailField(default='exampleblabla@mail.com', max_length=100, unique=True),
        ),
    ]
