# Generated by Django 3.0.6 on 2020-06-17 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='patients_guided_here',
        ),
        migrations.AddField(
            model_name='hospital',
            name='available_ventilators',
            field=models.IntegerField(default=0),
        ),
    ]
